
window.onerror=function(m,s,l,c,err){alert('JS ERROR: '+m+(' at line '+l+(','+c)};
const SK="try2_projects",CONFIG_FILE="upload_config.json";
let currentProjectIdx=-1,selectedDoc=null,selectedBase=null,currentView="upload",showInterpret=false,docDetailView=false,docDetailName="";
const projectHandles={},pendingFileObjects={};
const DB_NAME="project_handles_db",DB_VER=1;
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{r.result.createObjectStore("handles")};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbPut(n,h){const db=await openDB(),tx=db.transaction("handles","readwrite");tx.objectStore("handles").put(h,n);return new Promise((res,rej)=>{tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function dbGet(n){const db=await openDB(),tx=db.transaction("handles","readonly"),r=tx.objectStore("handles").get(n);return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbDelete(n){const db=await openDB(),tx=db.transaction("handles","readwrite");tx.objectStore("handles").delete(n);return new Promise((res,rej)=>{tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function dbGetAll(){const db=await openDB(),tx=db.transaction("handles","readonly"),r=tx.objectStore("handles").openCursor(),m={};return new Promise((res,rej)=>{r.onsuccess=()=>{const c=r.result;if(c){m[c.key]=c.value;c.continue()}else res(m)};r.onerror=()=>rej(r.error)})}
async function restoreHandles(){try{const m=await dbGetAll();for(const[n,h]of Object.entries(m))projectHandles[n]=h}catch(e){}renderList()}
function L(){try{return JSON.parse(localStorage.getItem(SK))||[]}catch{return[]}}
function S(v){localStorage.setItem(SK,JSON.stringify(v))}
function E(s){const d=document.createElement("div");d.textContent=s;return d.innerHTML}
function renderList(){const a=L(),c=document.getElementById("list");if(!a.length){c.innerHTML="<div class=\"empty\">暂无项目，点击上方按钮添加</div>";return}c.innerHTML=a.map((p,i)=>"<div class=\"project-card\" data-i=\""+i+"\"><div class=\"project-info\"><div class=\"project-name\">"+E(p.name)+"</div><div class=\"project-path\">"+E(p.path)+"</div></div><button class=\"btn-del-project\" data-i=\""+i+"\" title=\"删除项目\">✕</button><span class=\"project-arrow\">›</span></div>").join("")}
async function showDetail(){const p=L()[currentProjectIdx];if(!p)return;selectedDoc=null;selectedBase=null;currentView="upload";showInterpret=false;document.getElementById("listView").classList.add("hidden");document.getElementById("detailView").classList.remove("hidden");document.getElementById("detailTitle").textContent=p.name;switchView("upload")}
function showList(){document.getElementById("detailView").classList.add("hidden");document.getElementById("listView").classList.remove("hidden");const p=L()[currentProjectIdx];if(p)delete pendingFileObjects[p.name];currentProjectIdx=-1;selectedDoc=null;selectedBase=null;showInterpret=false;renderList()}
async function getHandle(name){if(projectHandles[name]){try{if((await projectHandles[name].queryPermission({mode:"readwrite"}))==="granted")return projectHandles[name];if((await projectHandles[name].requestPermission({mode:"readwrite"}))==="granted")return projectHandles[name]}catch(e){}}try{const h=await dbGet(name);if(h){projectHandles[name]=h;if((await h.queryPermission({mode:"readwrite"}))==="granted")return h;if((await h.requestPermission({mode:"readwrite"}))==="granted")return h}}catch(e){}return null}
function switchView(view){currentView=view;showInterpret=false;["upload","codeversion","docversion"].forEach(v=>document.getElementById(v+"View").classList.toggle("hidden",v!==view));document.querySelectorAll(".detail-tab").forEach(t=>t.classList.toggle("active",t.dataset.view===view));if(view==="upload"){renderUploads();loadSfDocs();loadCodeVersions()}else if(view==="codeversion")loadCodeVersion();else if(view==="docversion")loadDocVersion()}
async function readCodeConfig(name){const h=await getHandle(name);if(!h)return[];try{const cd=await h.getDirectoryHandle("code");const fh=await cd.getFileHandle(CONFIG_FILE);const f=await fh.getFile();const t=await f.text();return JSON.parse(t).entries||[]}catch(e){return[]}}
async function writeCodeConfig(name,entries){const h=await getHandle(name);if(!h)return;const cd=await h.getDirectoryHandle("code",{create:true});const fh=await cd.getFileHandle(CONFIG_FILE,{create:true});const ws=await fh.createWritable();await ws.write(JSON.stringify({entries},null,2));await ws.close()}
/* === right panel delegation === */
document.getElementById("sfDocList").addEventListener("click",e=>{const el=e.target.closest(".sf-file");if(!el)return;selectedDoc=(selectedDoc===el.dataset.name)?null:el.dataset.name;renderSfChecks();updateSelectedBar()});
document.getElementById("sfCodeVerList").addEventListener("click",e=>{const el=e.target.closest(".sf-file");if(!el)return;selectedBase=(selectedBase===el.dataset.name)?null:el.dataset.name;renderSfChecks();updateSelectedBar()});
async function loadSfDocs(){const p=L()[currentProjectIdx],c=document.getElementById("sfDocList");if(!p){c.innerHTML="<div class=\"sf-empty\">暂无数据</div>";return}const h=await getHandle(p.name);if(!h){c.innerHTML="<div class=\"sf-empty\">请重新授权</div>";return}try{const sf=await h.getDirectoryHandle("sf"),files=[];for await(const[n,entry]of sf.entries()){if(entry.kind==="file")files.push(n)}files.sort((a,b)=>a.localeCompare(b));if(!files.length){c.innerHTML="<div class=\"sf-empty\">暂无文档</div>";renderSfChecks();updateSelectedBar();return}c.innerHTML=files.map(n=>{const sel=selectedDoc===n?" selected":"";return"<div class=\"sf-file"+sel+"\" data-name=\""+E(n)+"\"><div class=\"sf-check"+sel+"\"><svg viewBox=\"0 0 24 24\"><path d=\"M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z\"/></svg></div><svg class=\"doc-icon\" viewBox=\"0 0 24 24\"><path d=\"M14 2H6c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V8l-6-6zM6 20V4h7v5h5v11H6z\"/></svg><span class=\"sf-file-name\" title=\""+E(n)+"\">"+E(n)+"</span></div>"}).join("");renderSfChecks();updateSelectedBar()}catch(e){c.innerHTML="<div class=\"sf-empty\">读取失败</div>"}}
async function loadCodeVersions(){const p=L()[currentProjectIdx],c=document.getElementById("sfCodeVerList");if(!p){c.innerHTML="<div class=\"sf-empty\">暂无数据</div>";return}const h=await getHandle(p.name);if(!h){c.innerHTML="<div class=\"sf-empty\">请重新授权</div>";return}try{const config=await readCodeConfig(p.name);const cd=await h.getDirectoryHandle("code"),items=[];for await(const[n,entry]of cd.entries()){if(entry.kind==="file"&&n!==CONFIG_FILE)items.push(n)}for(const ce of config){if(!items.includes(ce.codeFile))items.push(ce.codeFile)}items.sort((a,b)=>a.localeCompare(b));if(!items.length){c.innerHTML="<div class=\"sf-empty\">\u6682\u65e0\u7248\u672c</div>";renderSfChecks();updateSelectedBar();return}const cm={};for(const e of config)cm[e.codeFile]=e;c.innerHTML=items.map(n=>{const sel=selectedBase===n?" selected":"";const ce=cm[n];const doc=ce&&ce.linkedDoc?" <span class=\"sf-file-sub\">\u2192 "+E(ce.linkedDoc)+"</span>":"";return"<div class=\"sf-file"+sel+"\" data-name=\""+E(n)+"\"><div class=\"sf-check"+sel+"\"><svg viewBox=\"0 0 24 24\"><path d=\"M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z\"/></svg></div><svg class=\"code-icon\" viewBox=\"0 0 24 24\"><path d=\"M9.4 16.6L4.8 12l4.6-4.6L8 6l-6 6 6 6 1.4-1.4zm5.2 0l4.6-4.6-4.6-4.6L16 6l6 6-6 6-1.4-1.4z\"/></svg><span class=\"sf-file-name\" title=\""+E(n)+"\">"+E(n)+"</span>"+doc+"</div>"}).join("");renderSfChecks();updateSelectedBar();}catch(e){c.innerHTML="<div class=\"sf-empty\">读取失败</div>"}}
function renderSfChecks(){document.querySelectorAll("#sfDocList .sf-file").forEach(el=>{el.classList.toggle("selected",el.dataset.name===selectedDoc);const ck=el.querySelector(".sf-check");if(ck)ck.classList.toggle("selected",el.dataset.name===selectedDoc)});document.querySelectorAll("#sfCodeVerList .sf-file").forEach(el=>{el.classList.toggle("selected",el.dataset.name===selectedBase);const ck=el.querySelector(".sf-check");if(ck)ck.classList.toggle("selected",el.dataset.name===selectedBase)})}
function updateSelectedBar(){const bar=document.getElementById("sfSelectedBar");let h="";if(selectedDoc)h+='<span class="tag doc">文档：'+E(selectedDoc)+"</span>";if(selectedBase)h+='<span class="tag base">基版本：'+E(selectedBase)+"</span>";bar.innerHTML=h||"请选择关联的算法文档"}

/* === xlsx validation === */
function isHex(str){return /^0x[0-9a-fA-F]+$/.test(str)}
function validateXlsxRow(row){const errs=[];const A=String(row[0]||"").trim(),B=String(row[1]||"").trim(),C=String(row[2]||"").trim(),D=String(row[3]||"").trim(),E=String(row[4]||"").trim(),F=String(row[5]||"").trim();function chk(v,l){if(!v)return true;const p=v.split(/\s+/);for(const x of p){if(!isHex(x)){errs.push(l+" 的值 \""+v+"\" 包含非十六进制值");return false}}return true}chk(B,"IP开关寄存器起始地址");chk(C,"IP开寄存器状态值");chk(D,"IP关寄存器状态值");chk(E,"IP参数起始地址");chk(F,"IP参数结束地址");if(B){const p=B.split(/\s+/);if(p.length>1)errs.push("IP开关寄存器起始地址只能填一个值，当前有 "+p.length+" 个")}if(C&&D){const c=C.split(/\s+/).length,d=D.split(/\s+/).length;if(c!==d)errs.push("IP开寄存器状态值的数量("+c+")与IP关寄存器状态值的数量("+d+")不相等")}if((E&&!F)||(!E&&F))errs.push("IP参数起始地址与IP参数结束地址必须同时为空或同时有值");if(E&&F&&parseInt(E,16)>=parseInt(F,16))errs.push("IP参数起始地址("+E+")必须小于IP参数结束地址("+F+")");return errs}
async function validateXlsxFile(file){const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:"array"}),ws=wb.Sheets[wb.SheetNames[0]],json=XLSX.utils.sheet_to_json(ws,{header:1});const allErrs=[];for(let i=1;i<json.length;i++){const row=json[i];if(!row||!row[0])continue;for(const e of validateXlsxRow(row))allErrs.push("第"+(i+1)+"行: "+e)}return allErrs.length?{ok:false,errors:allErrs}:{ok:true}}
/* === render & interpret === */
function renderUploads(){const p=L()[currentProjectIdx];if(!p)return;renderFileList(p,"docs","docList","docEmpty","docFooter","confirmDocBtn",confirmDocs);renderFileList(p,"codes","codeList","codeEmpty","codeFooter","interpretCodeBtn",startInterpret)}
function renderFileList(p,key,listId,emptyId,footerId,btnId,fn){const items=p[key]||[],c=document.getElementById(listId);c.innerHTML=items.map((f,i)=>renderItem(f,i,key)).join("");document.getElementById(emptyId).style.display=items.length?"none":"block";const footer=document.getElementById(footerId);if(items.length&&!(key==="codes"&&showInterpret)){const isDoc=key==="docs";const hasInvalid=isDoc&&items.some(f=>f._valid===false);const label=isDoc?"确认上传":"开始解读";const cls=isDoc?"btn-confirm":"btn-interpret";footer.innerHTML='<button class="'+cls+'" id="'+btnId+'"'+(hasInvalid?" disabled":"")+"><svg viewBox=\"0 0 24 24\"><path d=\"M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z\"/></svg>"+label+"</button>";document.getElementById(btnId).addEventListener("click",fn)}else{footer.innerHTML=""}}
function renderItem(file,idx,key){if(key==="docs"){const st=file._valid===false?"invalid":(file._valid===true?"valid":""),dot=file._valid===false?"error":(file._valid===true?"ok":"");let msg="";if(file._errors&&file._errors.length)msg='<div class="upload-item-msg">'+E(file._errors.join("\n"))+"</div>";return'<div class="upload-item '+st+'"><div class="upload-item-left"><span class="upload-item-status '+dot+'"></span><span class="upload-item-name">'+E(file.name)+"</span>"+(file._valid===true?'<span class="upload-item-extra">格式校验通过</span>':"")+(file._valid===false?'<span class="upload-item-extra" style="color:#f56c6c">校验不通过</span>':"")+'</div><span class="upload-item-size">'+E(file.size)+'</span><button class="upload-item-remove" data-type="doc" data-i="'+idx+'" title="删除">✕</button></div>'+msg}return'<div class="upload-item"><div class="upload-item-left"><span class="upload-item-status"></span><span class="upload-item-name">'+E(file.name)+'</span></div><span class="upload-item-size">'+E(file.size)+'</span><button class="upload-item-remove" data-type="code" data-i="'+idx+'" title="删除">✕</button></div>'}
async function openFilePicker(multiple,accept){const i=document.createElement("input");i.type="file";i.multiple=multiple;if(accept)i.accept=accept;return new Promise(r=>{i.addEventListener("change",()=>r(i.files));i.click()})}
/* === interpret area === */
function startInterpret(){showInterpret=true;const p=L()[currentProjectIdx];if(!p)return;const codes=p.codes||[];if(!codes.length)return;const fl=document.getElementById("interpretFileList");fl.innerHTML=codes.map(f=>'<div class="interpret-file-item"><svg viewBox="0 0 24 24"><path d="M9.4 16.6L4.8 12l4.6-4.6L8 6l-6 6 6 6 1.4-1.4zm5.2 0l4.6-4.6-4.6-4.6L16 6l6 6-6 6-1.4-1.4z"/></svg><span>'+E(f.name)+"</span></div>").join("");document.getElementById("interpretArea").classList.remove("hidden");document.getElementById("codeFooter").innerHTML="";renderUploads()}
function cancelInterpret(){showInterpret=false;document.getElementById("interpretArea").classList.add("hidden");renderUploads()}

/* === project mgmt === */
async function addProject(){if(window.showDirectoryPicker){try{const h=await window.showDirectoryPicker();await h.getDirectoryHandle("code",{create:true});await h.getDirectoryHandle("sf",{create:true});const a=L();a.push({name:h.name,path:"已选择文件夹: "+h.name,docs:[],codes:[]});S(a);projectHandles[h.name]=h;await dbPut(h.name,h);renderList();return}catch(e){if(e.name!=="AbortError")throw e}}const i=document.createElement("input");i.type="file";i.webkitdirectory=true;i.style.display="none";i.addEventListener("change",()=>{if(!i.files||!i.files.length)return;const d=i.files[0].webkitRelativePath.split("/")[0];const a=L();a.push({name:d,path:"已选择文件夹: "+d+"（降级模式）",docs:[],codes:[]});S(a);renderList()});document.body.appendChild(i);i.click();i.remove()}
function removeProject(idx){const a=L(),p=a[idx];if(!p)return;if(projectHandles[p.name])delete projectHandles[p.name];if(pendingFileObjects[p.name])delete pendingFileObjects[p.name];dbDelete(p.name);a.splice(idx,1);S(a);if(currentProjectIdx===idx||currentProjectIdx>idx)currentProjectIdx=-1;renderList()}
/* === push / remove / confirm === */
async function pushFile(type,files){const p=L()[currentProjectIdx],key=type==="doc"?"docs":"codes";if(!p)return;if(!p[key])p[key]=[];const cfg=key==="codes"?await readCodeConfig(p.name):[];const cm={};for(const e of cfg)cm[e.codeFile]=e;for(const f of files){const it={name:f.name,size:formatSize(f.size)};if(key==="codes"){if(selectedDoc)it.linkedDoc=selectedDoc;if(selectedBase){it.baseVersion=selectedBase;const be=cm[selectedBase];if(be&&be.linkedDoc)it.baseVersionDoc=be.linkedDoc}}p[key].push(it)}if(!pendingFileObjects[p.name])pendingFileObjects[p.name]={};if(!pendingFileObjects[p.name][key])pendingFileObjects[p.name][key]=[];for(const f of files){pendingFileObjects[p.name][key].push(f)}const a=L();a[currentProjectIdx]=p;S(a);renderUploads();if(key==="docs"&&typeof XLSX!=="undefined"){const idx=p[key].length-files.length;for(let fi=0;fi<files.length;fi++){(function(f,di){validateXlsxFile(f).then(r=>{const pp=L()[currentProjectIdx];if(!pp)return;const dd=pp[key]||[];if(di<dd.length&&dd[di].name===f.name){dd[di]._valid=r.ok;if(!r.ok)dd[di]._errors=r.errors;const aa=L();aa[currentProjectIdx]=pp;S(aa);renderUploads()}})})(files[fi],idx+fi)}}}
function removeFile(type,idx){const p=L()[currentProjectIdx],key=type==="doc"?"docs":"codes";if(!p||!p[key])return;p[key].splice(idx,1);if(pendingFileObjects[p.name]?.[key])pendingFileObjects[p.name][key].splice(idx,1);if(!p[key].length&&key==="codes"){showInterpret=false;document.getElementById("interpretArea").classList.add("hidden")}const a=L();a[currentProjectIdx]=p;S(a);renderUploads()}
async function confirmUpload(subDir,key){const p=L()[currentProjectIdx];if(!p)return;if(key==="docs"){if((p[key]||[]).some(f=>f._valid===false)){alert("存在校验不通过的文档，请修正后重试");return}}const h=await getHandle(p.name);if(!h){alert("无法访问项目目录，请返回列表重新进入项目以授权");return}const pending=p[key]||[];if(!pending.length)return;try{const dh=await h.getDirectoryHandle(subDir,{create:true});const existing=new Set();for await(const[n]of dh.entries())existing.add(n);const fo=pendingFileObjects[p.name]?.[key]||[];const conflicts=[],written=[];for(let i=0;i<pending.length;i++){const m=pending[i];if(existing.has(m.name)){conflicts.push(m.name);continue}const f=fo[i];if(!f)continue;const d=await f.arrayBuffer();const fh=await dh.getFileHandle(m.name,{create:true});const ws=await fh.createWritable();await ws.write(d);await ws.close();written.push(m.name)}if(key==="codes"&&written.length){const ec=await readCodeConfig(p.name);const es=new Set(ec.map(e=>e.codeFile+"|||"+e.linkedDoc+"|||"+e.baseVersion+"|||"+e.baseVersionDoc));for(const d of pending){if(written.includes(d.name)){const k=d.name+"|||"+(d.linkedDoc||"")+"|||"+(d.baseVersion||"")+"|||"+(d.baseVersionDoc||"");if(!es.has(k)){ec.push({codeFile:d.name,uploadedAt:new Date().toISOString(),linkedDoc:d.linkedDoc||"",baseVersion:d.baseVersion||"",baseVersionDoc:d.baseVersionDoc||""});es.add(k)}}}await writeCodeConfig(p.name,ec)}p[key]=[];if(pendingFileObjects[p.name])delete pendingFileObjects[p.name][key];showInterpret=false;document.getElementById("interpretArea").classList.add("hidden");const a=L();a[currentProjectIdx]=p;S(a);renderUploads();loadSfDocs();loadCodeVersions();selectedDoc=null;selectedBase=null;renderSfChecks();updateSelectedBar();let msg="";if(written.length)msg+=written.length+" 个文件已上传到 "+subDir+"/";if(conflicts.length)msg+="\n因重名跳过："+conflicts.join("、");if(msg)alert(msg);else alert("没有文件被上传")}catch(e){alert("写入失败："+e.message)}}
function confirmDocs(){confirmUpload("sf","docs")}
function confirmCodes(){confirmUpload("code","codes")}
/* === version views === */
async function loadCodeVersion(){const p=L()[currentProjectIdx],ct=document.getElementById("codeversionContent");if(!p){ct.innerHTML="<div class=\"empty\">暂无数据</div>";return}const h=await getHandle(p.name);if(!h){ct.innerHTML="<div class=\"empty\">请重新授权</div>";return}try{const config=await readCodeConfig(p.name),cm={};for(const e of config)cm[e.codeFile]=e;const cd=await h.getDirectoryHandle("code"),items=[];for await(const[n,entry]of cd.entries()){if(entry.kind==="file"&&n!==CONFIG_FILE){const f=await entry.getFile(),ce=cm[n];items.push({name:n,uploadedAt:ce?ce.uploadedAt:null,linkedDoc:ce?ce.linkedDoc:"",baseVersion:ce?ce.baseVersion:"",lastModified:f.lastModified})}}for(const ce of config)if(!items.find(i=>i.name===ce.codeFile))items.push({name:ce.codeFile,uploadedAt:ce.uploadedAt,linkedDoc:ce.linkedDoc,baseVersion:ce.baseVersion,lastModified:0});items.sort((a,b)=>(b.uploadedAt||new Date(b.lastModified).toISOString()).localeCompare(a.uploadedAt||new Date(a.lastModified).toISOString()));if(!items.length){ct.innerHTML="<div class=\"empty\">暂无代码版本信息</div>";return}ct.innerHTML='<table class="version-table"><thead><tr><th>Code 名称</th><th>上传时间</th><th>算法文档</th><th>Base 版本</th><th>操作</th></tr></thead><tbody>'+items.map((it,i)=>'<tr><td class="cell-name">'+E(it.name)+'</td><td class="cell-time">'+E(it.uploadedAt?formatTime(it.uploadedAt):formatTime(new Date(it.lastModified).toISOString()))+'</td><td class="cell-doc">'+E(it.linkedDoc||"-")+'</td><td class="cell-base">'+E(it.baseVersion+(it.baseVersionDoc?" <span class=\"version-sub\">\u2192 "+E(it.baseVersionDoc)+"</span>":"")||"首版")+'</td><td class="cell-action">'+(!i?'<button class="btn-del-version" data-name="'+E(it.name)+'" title="删除最新版本"><svg viewBox="0 0 24 24"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>删除</button>':'')+'</td></tr>').join("")+"</tbody></table>"}catch(e){ct.innerHTML="<div class=\"empty\">读取失败</div>"}}
async function loadDocVersion(){const p=L()[currentProjectIdx],ct=document.getElementById("docversionContent");if(!p){ct.innerHTML="<div class=\"empty\">暂无数据</div>";return}const h=await getHandle(p.name);if(!h){ct.innerHTML="<div class=\"empty\">请重新授权</div>";return}try{const sf=await h.getDirectoryHandle("sf"),items=[];for await(const[n,entry]of sf.entries()){if(entry.kind==="file"){const f=await entry.getFile();items.push({name:n,size:formatSize(f.size),lastModified:f.lastModified})}}items.sort((a,b)=>(b.lastModified||0)-(a.lastModified||0));if(!items.length){ct.innerHTML="<div class=\"empty\">暂无算法文档</div>";return}ct.innerHTML='<table class="version-table"><thead><tr><th>文档名称</th><th>大小</th><th>上传时间</th><th>操作</th></tr></thead><tbody>'+items.map((it,i)=>'<tr><td class="cell-name">'+E(it.name)+'</td><td class="cell-size">'+E(it.size)+'</td><td class="cell-time">'+E(formatTime(new Date(it.lastModified).toISOString()))+'</td><td class="cell-action">'+('<button class="btn-act btn-edit" data-name="'+E(it.name)+'" title="编辑"><svg viewBox="0 0 24 24"><path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/></svg>编辑</button><button class="btn-act btn-del" data-name="'+E(it.name)+'" title="删除"><svg viewBox="0 0 24 24"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>删除</button>')+'</td></tr>').join("")+"</tbody></table>"}catch(e){ct.innerHTML="<div class=\"empty\">读取失败</div>"}}
function formatTime(iso){if(!iso)return"-";try{const d=new Date(iso),pad=n=>String(n).padStart(2,"0");return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate())+" "+pad(d.getHours())+":"+pad(d.getMinutes())}catch(e){return iso}}
function formatSize(bytes){if(bytes<1024)return bytes+" B";if(bytes<1048576)return(bytes/1024).toFixed(1)+" KB";return(bytes/1048576).toFixed(1)+" MB"}
/* === delete version === */
async function deleteVersion(name){const p=L()[currentProjectIdx];if(!p)return;const h=await getHandle(p.name);if(!h){alert("无法访问项目目录");return}try{const cd=await h.getDirectoryHandle("code");await cd.removeEntry(name);const cfg=await readCodeConfig(p.name);const idx=cfg.findIndex(e=>e.codeFile===name);if(idx>=0){cfg.splice(idx,1);await writeCodeConfig(p.name,cfg)}loadCodeVersion()}catch(e){alert("删除失败："+e.message)}}

﻿/* === doc actions === */
async function deleteDoc(name){const p=L()[currentProjectIdx];if(!p)return;const h=await getHandle(p.name);if(!h){alert("无法访问项目目录");return}try{const sf=await h.getDirectoryHandle("sf");await sf.removeEntry(name);loadDocVersion();loadSfDocs()}catch(e){alert("删除失败："+e.message)}}
function renderIpGroups(){const ct=document.getElementById("docversionContent");if(!ipGroups.length){ct.innerHTML='<div class="detail-bar"><div class="detail-bar-left"><button class="btn-back" onclick="backDocList()"><svg viewBox="0 0 24 24" width="14" height="14"><path d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z"/></svg> 返回</button><span style="font-size:16px;font-weight:600">'+E(docDetailName)+'</span></div><div class="detail-bar-right"><button class="btn-add-ip" onclick="addIpGroup()"><svg viewBox="0 0 24 24" width="14" height="14"><path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/></svg> 新增IP组</button><button class="btn-save" onclick="saveIpGroups()">保存</button></div></div><div class="ip-group-empty">暂无IP组，点击上方&#39;新增IP组&#39;添加</div>';return}let html='<div class="detail-bar"><div class="detail-bar-left"><button class="btn-back" onclick="backDocList()"><svg viewBox="0 0 24 24" width="14" height="14"><path d="M20 11H7.83l5.59-5.59L12 4l-8 8 8 8 1.41-1.41L7.83 13H20v-2z"/></svg> 返回</button><span style="font-size:16px;font-weight:600">'+E(docDetailName)+'</span></div><div class="detail-bar-right"><button class="btn-add-ip" onclick="addIpGroup()"><svg viewBox="0 0 24 24" width="14" height="14"><path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/></svg> 新增IP组</button><button class="btn-save" onclick="saveIpGroups()">保存</button></div></div><div id="ipGroupContainer">';for(let i=0;i<ipGroups.length;i++){const g=ipGroups[i];const ed=i===editingIdx;html+='<div class="ip-group-card"><div class="ip-group-header"><span>IP组 '+(i+1)+'</span><div>'+(ed?'<button class="btn-act btn-save" style="padding:4px 10px;font-size:11px" onclick="saveIpGroup('+i+')">保存</button>':'<button class="btn-act btn-edit" onclick="editIpGroup('+i+')" title="编辑"><svg viewBox="0 0 24 24" width="12" height="12"><path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04c.39-.39.39-1.02 0-1.41l-2.34-2.34c-.39-.39-1.02-.39-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83z"/></svg>编辑</button>')+'<button class="btn-act btn-del-ip" onclick="deleteIpGroup('+i+')" title="删除"><svg viewBox="0 0 24 24" width="12" height="12"><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/></svg>删除</button></div></div><div class="ip-group-body">';html+='<div class="ip-group-body">';const lbs=['IP名称','IP开关寄存器起始地址','IP开寄存器状态值','IP关寄存器状态值','IP参数起始地址','IP参数结束地址'];const kys=['A','B','C','D','E','F'];html+='<div style="display:flex;gap:6px;width:100%;flex-wrap:nowrap">';for(let fi=0;fi<6;fi++){const lb=lbs[fi];const ky=kys[fi];const val=g[ky]||"";html+='<div class="ip-field"><div class="ip-badge">'+(fi+1)+'</div><div class="ip-label">'+lb+'</div>';if(ed){html+='<input id="ipf_'+i+'_'+ky+'" value="'+E(val)+'" />'}else{html+='<div class="ip-val">'+E(val||"-")+'</div>'}html+='</div>'}html+='</div>';html+='</div></div>'}html+='</div>';ct.innerHTML=html}
function backDocList(){docDetailView=false;docDetailName="";ipGroups=[];editingIdx=-1;loadDocVersion()}
function addIpGroup(){ipGroups.unshift({A:"",B:"",C:"",D:"",E:"",F:""});editingIdx=0;renderIpGroups();const el=document.getElementById("ipGroupContainer");if(el)el.scrollIntoView({behavior:"smooth"})}
function editIpGroup(idx){editingIdx=idx;renderIpGroups()}
function saveIpGroup(idx){const g=ipGroups[idx];g.A=document.getElementById("ipf_"+idx+"_A").value;g.B=document.getElementById("ipf_"+idx+"_B").value;g.C=document.getElementById("ipf_"+idx+"_C").value;g.D=document.getElementById("ipf_"+idx+"_D").value;g.E=document.getElementById("ipf_"+idx+"_E").value;g.F=document.getElementById("ipf_"+idx+"_F").value;const e=ipv(ipGroups,idx);if(e.length){alert("校验失败：\n"+e.join("\n"));return}editingIdx=-1;renderIpGroups()}
function deleteIpGroup(idx){if(!confirm("确定要删除该IP组吗？"))return;ipGroups.splice(idx,1);if(editingIdx>=ipGroups.length||editingIdx===idx)editingIdx=-1;renderIpGroups()}
function ipv(arr,skipIdx){const errs=[];for(let i=0;i<arr.length;i++){if(i===skipIdx)continue;const g=arr[i];if(!g.A&&!g.B&&!g.C&&!g.D&&!g.E&&!g.F)continue;const r=/^0x[0-9a-fA-F]+$/;var ck=function(v,l){if(!v)return;const p=v.split(/\s+/);for(const x of p){if(!r.test(x)){errs.push("第"+(i+1)+"行 "+l+": \""+v+"\" 非十六进制");return}}};ck(g.B,"IP开关寄存器起始地址");ck(g.C,"IP开寄存器状态值");ck(g.D,"IP关寄存器状态值");ck(g.E,"IP参数起始地址");ck(g.F,"IP参数结束地址");if(g.B&&g.B.split(/\s+/).length>1)errs.push("第"+(i+1)+"行 IP开关寄存器起始地址只能填一个值");if(g.C&&g.D){const c=g.C.split(/\s+/).length,d=g.D.split(/\s+/).length;if(c!==d)errs.push("第"+(i+1)+"行 开数量("+c+")与关数量("+d+")不相等")}if((g.E&&!g.F)||(!g.E&&g.F))errs.push("第"+(i+1)+"行 起始地址与结束地址必须同时为空或同时有值");if(g.E&&g.F&&parseInt(g.E,16)>=parseInt(g.F,16))errs.push("第"+(i+1)+"行 起始地址("+g.E+")必须小于结束地址("+g.F+")")}return errs}
async function saveIpGroups(){for(let i=0;i<ipGroups.length;i++){const g=ipGroups[i];if(editingIdx===i){g.A=document.getElementById("ipf_"+i+"_A").value;g.B=document.getElementById("ipf_"+i+"_B").value;g.C=document.getElementById("ipf_"+i+"_C").value;g.D=document.getElementById("ipf_"+i+"_D").value;g.E=document.getElementById("ipf_"+i+"_E").value;g.F=document.getElementById("ipf_"+i+"_F").value}}const errs=ipv(ipGroups,-1);if(errs.length){alert("保存校验失败：\n"+errs.join("\n"));return}const ov=document.getElementById("docversionContent");ov.innerHTML='<div class="saving-overlay">保存中...</div>';try{const p=L()[currentProjectIdx];const h=await getHandle(p.name);const sf=await h.getDirectoryHandle("sf");const fh=await sf.getFileHandle(docDetailName,{create:true});const hdr=["IP名称","IP开关寄存器起始地址","IP开寄存器状态值","IP关寄存器状态值","IP参数起始地址","IP参数结束地址"];const data=[hdr];for(const g of ipGroups)data.push([g.A,g.B,g.C,g.D,g.E,g.F]);const ws=XLSX.utils.aoa_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Sheet1");const wbOut=XLSX.write(wb,{type:"array",bookType:"xlsx"});const wr=await fh.createWritable();await wr.write(wbOut);await wr.close();editingIdx=-1;backDocList();loadSfDocs();alert("保存成功")}catch(e){alert("保存失败："+e.message);renderIpGroups()}}
/* === doc detail view === */
async function showDocDetail(name){const p=L()[currentProjectIdx];if(!p)return;const h=await getHandle(p.name);if(!h){alert("无法访问");return}try{const sf=await h.getDirectoryHandle("sf");const fh=await sf.getFileHandle(name);const f=await fh.getFile();const data=await f.arrayBuffer();const wb=XLSX.read(data,{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];const json=XLSX.utils.sheet_to_json(ws,{header:1});ipGroups=[];editingIdx=-1;docDetailName=name;for(let r=1;r<json.length;r++){const row=json[r];if(!row||!row[0])continue;ipGroups.push({A:String(row[0]||"").trim(),B:String(row[1]||"").trim(),C:String(row[2]||"").trim(),D:String(row[3]||"").trim(),E:String(row[4]||"").trim(),F:String(row[5]||"").trim()})}renderIpGroups()}catch(e){document.getElementById("docversionContent").innerHTML='<div class="empty">读取失败：'+e.message+'</div>'}}
/* === event bindings === */
document.getElementById("addBtn").addEventListener("click",addProject);
document.getElementById("backBtn").addEventListener("click",showList);
document.getElementById("uploadDocBtn").addEventListener("click",async()=>{const f=await openFilePicker(true,".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");if(f&&f.length)pushFile("doc",f)});
document.getElementById("uploadCodeBtn").addEventListener("click",async()=>{if(!selectedDoc){alert("请先选择一个关联的算法文档");return}const hasVer=document.querySelectorAll("#sfCodeVerList .sf-file").length>0;if(hasVer&&!selectedBase){alert("请先选择一个父版本（已上传的Code版本）");return}const f=await openFilePicker(true);if(f&&f.length)pushFile("code",f)});
document.getElementById("docList").addEventListener("click",e=>{const b=e.target.closest(".upload-item-remove");if(b&&b.dataset.type==="doc")removeFile("doc",parseInt(b.dataset.i))});
document.getElementById("codeList").addEventListener("click",e=>{const b=e.target.closest(".upload-item-remove");if(b&&b.dataset.type==="code")removeFile("code",parseInt(b.dataset.i))});
document.getElementById("interpretConfirmBtn").addEventListener("click",confirmCodes);
document.getElementById("list").addEventListener("click",e=>{const del=e.target.closest(".btn-del-project");if(del){if(confirm("确定要删除该项目吗？"))removeProject(parseInt(del.dataset.i));return}const card=e.target.closest(".project-card");if(card){currentProjectIdx=parseInt(card.dataset.i);showDetail()}});
document.querySelectorAll(".detail-tab").forEach(t=>t.addEventListener("click",()=>switchView(t.dataset.view)));
document.getElementById("refreshCodeBtn").addEventListener("click",loadCodeVersion);
document.getElementById("codeversionContent").addEventListener("click",e=>{const b=e.target.closest(".btn-del-version");if(b&&confirm("确定要删除版本 "+E(b.dataset.name)+" 吗？只能从最新版本开始删除。"))deleteVersion(b.dataset.name)});
document.getElementById("refreshDocBtn").addEventListener("click",loadDocVersion);
document.getElementById("docversionContent").addEventListener("click",e=>{const b=e.target.closest(".btn-edit");if(b){showDocDetail(b.dataset.name)}const d=e.target.closest(".btn-del");if(d&&confirm("确定要删除算法文档 "+E(d.dataset.name)+" 吗？")){deleteDoc(d.dataset.name)}});
restoreHandles();

void 0;